spring:
  kafka:
    consumer:
      group-id: test-group
  application:
    name: crm
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: crm
    password: secret
pnc:
  security:
    jwt-secret: test-secret
crm:
  kafka:
    customer-events-topic: customer-events
