spring:
  application:
    name: crm
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: crm
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
